config/urls.py
from django.contrib import admin
from django.urls import path, include
from students.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('students.urls')),
    path('', home, name='home'),
    path('teacher/', include('teachers.urls')),
    path('', home, name='home'),
    path('group/', include('groups.urls')),
    path('', home, name='home'),
]

groups/urls.py
from django.urls import path
from . import views


app_name = 'groups'

urlpatterns = [
    path('list/', views.group_list, name='list'),
    path('create/', views.group_create, name='create'),
    path('group/detail/<int:pk>/', views.group_detail, name='detail'),
    path('group/delete/<int:pk>/', views.group_delete, name='delete'),
]

students/urls.py
from django.urls import path
from . import views


app_name = 'students'

urlpatterns = [
    path('list/', views.student_list, name='list'),
    path('create/', views.student_create, name='create'),
    path('student/detail/<int:pk>/', views.student_detail, name='detail'),
    path('student/delete/<int:pk>/', views.student_delete, name='delete'),
]

teachers/urls.py
from django.urls import path
from . import views


app_name = 'teachers'

urlpatterns = [
    path('list/', views.teacher_list, name='list'),
    path('create/', views.teacher_create, name='create'),
    path('teacher/detail/<int:pk>/', views.teacher_detail, name='detail'),
    path('teacher/delete/<int:pk>/', views.teacher_delete, name='delete'),
]

groups/models.py
from django.db import models


class Group(models.Model):
    group_name = models.CharField(max_length=100)
    group_type = models.CharField(max_length=100)

students/models.py
from django.db import models


class Student(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    age = models.PositiveIntegerField()
    email = models.EmailField()

teachers/models.py
from django.db import models


class Teacher(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)

groups/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Group


def home(request):
    return render(request, 'index.html')


def group_list(request):
    groups = Group.objects.all()
    ctx = {'groups': groups}
    return render(request, 'groups/group-list.html', ctx)


def group_create(request):
    if request.method == 'POST':
        group_name = request.POST.get('group_name')
        group_type = request.POST.get('group_type')



        if (group_name and group_type):
            Group.objects.create(
                group_name=group_name,
                group_type=group_type,

            )
            return redirect('groups:list')

    return render(request, 'groups/group-form.html')



def group_detail(request, pk):
    group = get_object_or_404(Group, pk=pk)
    ctx = {'group': group}
    return render(request, 'groups/group-detail.html', ctx)


def group_delete(request, pk):
    group = get_object_or_404(Group, pk=pk)
    group.delete()
    return redirect('groups:list')

students/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Student


def home(request):
    return render(request, 'index.html')


def student_list(request):
    students = Student.objects.all()
    ctx = {'students': students}
    return render(request, 'students/student-list.html', ctx)


def student_create(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        age = request.POST.get('age')
        email = request.POST.get('email')


        if (first_name and last_name and age and email):
            Student.objects.create(
                first_name=first_name,
                last_name=last_name,
                age=age,
                email=email
            )
            return redirect('students:list')

    return render(request, 'students/student-form.html')



def student_detail(request, pk):
    student = get_object_or_404(Student, pk=pk)
    ctx = {'student': student}
    return render(request, 'students/student-detail.html', ctx)


def student_delete(request, pk):
    student = get_object_or_404(Student, pk=pk)
    student.delete()
    return redirect('students:list')

teachers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Teacher


def home(request):
    return render(request, 'index.html')


def teacher_list(request):
    teachers = Teacher.objects.all()
    ctx = {'teachers': teachers}
    return render(request, 'teachers/teacher-list.html', ctx)


def teacher_create(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        subject = request.POST.get('subject')



        if (first_name and last_name and subject):
            Teacher.objects.create(
                first_name=first_name,
                last_name=last_name,
                subject=subject,
            )
            return redirect('teachers:list')

    return render(request, 'teachers/teacher-form.html')



def teacher_detail(request, pk):
    teacher = get_object_or_404(Teacher, pk=pk)
    ctx = {'teacher': teacher}
    return render(request, 'teachers/teacher-detail.html', ctx)


def teacher_delete(request, pk):
    teacher = get_object_or_404(Teacher, pk=pk)
    teacher.delete()
    return redirect('teachers:list')

templates/groups/group-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ group.group_name }} {{ group.group_type }}</title>
</head>
<body>
    <h1>{{ group.group_name }} {{ group.group_type }}</h1>
    <h3>Name: {{ group.group_name }}</h3>
    <h3>Type: {{ group.group_type }}</h3>
    <button><a href=" {% url 'groups:delete' pk=group.pk %}">Delete</a></button>
    <button><a href=" {% url 'groups:list' %}">Back to Group List</a></button>


</body>
</html>

templates/groups/group-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Group</title>
</head>
<body>
    <h1>Group Detail</h1>
    <form method="post">
        {% csrf_token %}
        <label for="group_name">Group Name</label><br>
        <input type="text" name="group_name" id="group_name"><br><br>
        <label for="group_type">Group Type</label><br>
        <input type="text" name="group_type" id="group_type"><br>
        <br>
        <button type="submit">Create Group</button>
    </form>
    <br><br>
    <button><a href="{% url 'groups:list' %}">Back to Group List</a></button>
</body>
</html>

templates/groups/group-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Group List</title>
</head>
<body>
    <h1>Group List</h1>
    <button><a href="{% url 'home' %}">Back to home</a></button>
    <button><a href="{% url 'groups:create' %}">Create group</a></button>
    {% for group in groups %}
        <a href="{% url 'groups:detail' pk=group.pk %}">
            <h3>{{ group.group_name }} {{ group.group_type }}</h3>
        </a>
    {% empty %}
        <h3>No groups</h3>
    {% endfor %}
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
</head>
<body>
    <h1>Home page</h1>
    <a href="{% url 'students:list' %}">Student List</a><br>
    <a href="{% url 'teachers:list' %}">Teacher List</a><br>
    <a href="{% url 'groups:list' %}">Group List</a><br>
</body>
</html>

templates/students/student-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ student.first_name }} {{ student.last_name }}</title>
</head>
<body>
    <h1>{{ student.first_name }} {{ student.last_name }}</h1>
    <h3>Age: {{ student.age }}</h3>
    <h3>Email: {{ student.email }}</h3>
    <button><a href=" {% url 'students:delete' pk=student.pk %}">Delete</a></button>
    <button><a href=" {% url 'students:list' %}">Back to Student List</a></button>


</body>
</html>

templates/students/student-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student</title>
</head>
<body>
    <h1>Student Detail</h1>
    <form method="post">
        {% csrf_token %}
        <label for="first_name">First Name</label><br>
        <input type="text" name="first_name" id="first_name"><br><br>
        <label for="last_name">Last Name</label><br>
        <input type="text" name="last_name" id="last_name"><br>
        <label for="age">Age</label><br>
        <input type="number" name="age" id="age"><br><br>
        <label for="email">Email</label><br>
        <input type="text" name="email" id="email"><br><br>
        <br>
        <button type="submit">Create Student</button>
    </form>
    <br><br>
    <button><a href="{% url 'students:list' %}">Back to Student List</a></button>
</body>
</html>

templates/students/student-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student List</title>
</head>
<body>
    <h1>Student List</h1>
    <button><a href="{% url 'home' %}">Back to home</a></button>
    <button><a href="{% url 'students:create' %}">Create student</a></button>
    {% for student in students %}
        <a href="{% url 'students:detail' pk=student.pk %}">
            <h3>{{ student.first_name }} {{ student.last_name }}</h3>
        </a>
    {% empty %}
        <h3>No students</h3>
    {% endfor %}
</body>
</html>

templates/teachers/teacher-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ teacher.first_name }} {{ teacher.last_name }}</title>
</head>
<body>
    <h1>{{ teacher.first_name }} {{ teacher.last_name }}</h1>
    <h3>Subject: {{ teacher.subject }}</h3>
    <button><a href=" {% url 'teachers:delete' pk=teacher.pk %}">Delete</a></button>
    <button><a href=" {% url 'teachers:list' %}">Back to Teacher List</a></button>


</body>
</html>

templates/teachers/teacher-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher</title>
</head>
<body>
    <h1>Teacher Detail</h1>
    <form method="post">
        {% csrf_token %}
        <label for="first_name">First Name</label><br>
        <input type="text" name="first_name" id="first_name"><br><br>
        <label for="last_name">Last Name</label><br>
        <input type="text" name="last_name" id="last_name"><br>
        <label for="subject">Subject</label><br>
        <input type="text" name="subject" id="subject"><br><br>
        <br>
        <button type="submit">Create Teacher</button>
    </form>
    <br><br>
    <button><a href="{% url 'teachers:list' %}">Back to Teacher List</a></button>
</body>
</html>

templates/teachers/teacher-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher List</title>
</head>
<body>
    <h1>Teacher List</h1>
    <button><a href="{% url 'home' %}">Back to home</a></button>
    <button><a href="{% url 'teachers:create' %}">Create Teacher</a></button>
    {% for teacher in teachers %}
        <a href="{% url 'teachers:detail' pk=teacher.pk %}">
            <h3>{{ teacher.first_name }} {{ teacher.last_name }}</h3>
        </a>
    {% empty %}
        <h3>No teachers</h3>
    {% endfor %}
</body>
</html>